# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'user',
                'verbose_name': '\u7528\u6237\u8868',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
    ]
