# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.EmailField(max_length=45),
        ),
    ]
